name: ci

on: push


jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: rust:1.66.1

    steps:
    - uses: actions/checkout@v3

    - name: check system
      run: |
        lscpu

    - name: run
      run: |
        cargo run --release